# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff48207abb59051ca1da5501aea8d68177b3ca1a45900278101a90d34c7c58af7f857099e4743c8e6bb877c5dc7e31cd61def183947ebe51cc99b678e198643

test:
  secret_key_base: 593c8e8cd8969ab61da3b6df7497d4af57f5c2029b9562961e86484b93bd1dc21fc98aeb2ac863ad799bbb322c55ca6d06709fbedb1837e800ead07c8f2a903f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
